### PR TITLE
Added "Modals" category and some packages

### PR DESCRIPTION
**Pull request by javisperez**
Packages added:

- Vuedals
- Vue-Dialog
- Vue-Longpress
- Vue-Visible

All for Vue 2

### CODE REVIEW

**Comment by brillout** [comment]
Thanks for the PR!

 - Vuedals -> good
 - I'd say that Vue-Dialog is too specific -> if someone wants such functionality then he should compose Vuedals + Vue-Longpress
 - Vue-Visible -> good but would fit better `UI Utilities -> Miscellaneous`
 - Vue-Longpress -> good, neat idea, I like it
 - Would be nice to have a note for npm installation for all your packages

**Comment by javisperez** [comment]
Hey, thx for the feedback @brillout i've added the npm install note on all the packages, removed vue-dialog because is too specific and moved Vue-visible to UI Utilities -> Miscellaneous.

Question: is there any way i can get vue-dialog included in the list? i mean, you say is too specific, is there something i can do about it? the idea is a really simple to use dialog window but you're right, it depends heavily on Vuedals and VueLongpress.

Thank you!

**Comment by brillout** [comment]
👍 

 - How about putting the hard press button component in `UI Components > Form > Miscellaneous`? (Instead of `UI Components > Miscellaneous`)
 - `vue-keyboard` is being removed by your PR, maybe rebase your commits on top of origin/master?
 - As for Vue-Dialog, maybe include its functionality to Vuedals?

**Comment by javisperez** [comment]
Ok done :) rebased everything and moved the hard press button to UI Components > Form > Miscellaneous. Also nvm about Vue-Dialog i don't think it fits as part of Vuedals, so I'll just leave it out.

**Pull request merged**
